### ISSUE TITLE
Assignement filtering not applied in production

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-gradebook#2]
![assignment_grade_filtering](https://user-images.githubusercontent.com/13796098/109296991-2c783600-7829-11eb-8518-4c2e341c5f79.gif)

**Comment by Salik-Rafiq** [comment]
I was seeing a exception in the console. Have tracked it down to a typo.  developer left the '.props.' in two places.

Will push this up for review shortly.

**Comment by Salik-Rafiq** [comment]
Created a pull request.
