### ISSUE TITLE
Overall Grade filtering not applied

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-gradebook#3]
![overall_grade_filtering](https://user-images.githubusercontent.com/13796098/109297076-56c9f380-7829-11eb-9c35-e54b43e7289b.gif)

**Comment by Salik-Rafiq** [comment]
The query parameters are being properly sent as far as I can tell. A manual Get on the URL shows that the same results that we are seeing on the UI.

Can't see anything in the Python code that is obvious. It gets the parameters, converts to a percent (float) and then calls a query method.

**Comment by BbrSofiane** [comment]
https://github.com/edx/edx-platform/blob/master/lms/djangoapps/grades/rest_api/v1/gradebook_views.py#L611

It seems that those filters are applied on PersistentCourseGrade and the actual overall grade is computed by default. See here: https://github.com/edx/edx-platform/blob/master/lms/djangoapps/grades/docs/decisions/0003-persistent-grades.rst

Persistent grades can be enabled in configuration. I've got it to work in dev setup.

**Comment by BbrSofiane** [comment]
Fixed in production
